services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: geronton
      POSTGRES_PASSWORD: geronton
      POSTGRES_DB: geronton
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
